config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do 
  post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root 'graphs#index'

  resource :graphs, only: %i[index create update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/graph.rb
class Graph < ApplicationRecord
  belongs_to :user
  validates :date, presence: true, uniqueness: { scope: :user_id }
  validates :yen, presence: true
  def self.chart_data(user)
    graphs = user.graphs.order(date: :asc)
    return [{ date: Date.today, yen: nil }] if graphs.empty?

    period = graphs[0].date..graphs[-1].date
    index = 0
    period.map do |date|
      if graphs[index].date == date
        yen = graphs[index].yen
        remain = graphs[index].remain
        index += 1
      end
      { date: date, yen: yen, remain: remain }
      end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :graphs, dependent: :destroy
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authenticate_user!

end

app/controllers/graphs_controller.rb
class GraphsController < ApplicationController
  def index
    gon.graph_records = Graph.chart_data(current_user)
    gon.recorded_dates = current_user.graphs.map(&:date)
  end

  def create
    @graph = current_user.graphs.build(graph_params)
    date = @graph.date.strftime('%Y/%-m/%-d')
    if @graph.save
      flash[:notice] = "#{date}の記録を追加しました"
    else
      flash[:alert] = 'エラーが発生しました'
    end
    redirect_to root_path
  end

  def update
    @graph = current_user.graphs.find_by(date: params[:graph][:date])
    date = @graph.date.strftime('%Y/%-m/%-d')
    if @graph.nil?
      flash[:alert] = 'エラーが発生しました'
    elsif params[:_destroy].nil? && @graph.update(graph_params)
      flash[:notice] = "#{date}の記録を修正しました。"
    elsif params[:_destroy].present? && @graph.destroy
      flash[:alert] = "#{date}の記録を削除しました。"
    else
      flash[:alert] = 'エラーが発生しました'
    end
    redirect_to root_path
  end

private
  def graph_params
  params.require(:graph).permit(:date, :yen, :remain)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/views/graphs/_edit_modal_content.html.erb
<%= form_with model: Graph.new, method: :patch do |form| %>
  <div class="input-group">
    <div class="input-group-prepend">
      <span class="input-group-text">日付</span>
    </div>
    <%= form.text_field :date, class: 'form-control bg-white', id: "edit-calendar" %>
  </div>
  <small>記録が存在しない日付は選択できません</small>
  <div class="input-group mt-3">
    <div class="input-group-prepend">
      <span class="input-group-text">金額</span>
    </div>
    <%= form.number_field :yen, class: 'form-control', id: "edit-yen", required: true %>
    <div class="ml-2 my-auto">yen</div>
  </div>
   <div class="input-group mt-3">
    <div class="input-group-prepend">
     <span class="input-group-text">予算</span>
    </div>
    <%= form.number_field :remain, class: 'form-control', id: "edit-remain", required: true %>
    <div class="ml-2 my-auto">remain</div>
  </div>

  <div class="form-group mt-3">
    <%= form.submit '修正', class: 'btn btn-primary btn-block mb-4', id: 'edit-button' %>
    <%= form.submit '削除', name: '_destroy', class: 'btn btn-danger btn-block', id: 'destroy-button', data: { confirm: "本当に記録を削除しますか？" } %>
  </div>
<% end %>

app/views/graphs/_modal.html.erb
<div class="modal fade" id="<%= action %>-modal" data-backdrop="static" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= title %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "#{action}_modal_content" %>
      </div>
    </div>
  </div>
</div>

app/views/graphs/_new_modal_content.html.erb
<%= form_with model: Graph.new do |form| %>
  <div class="input-group">
    <div class="input-group-prepend">
      <span class="input-group-text">日付</span>
    </div>
    <%= form.text_field :date, class: 'form-control bg-white', id: "new-calendar" %>
  </div>
  <small>記録が存在する日付は選択できません</small>
  <div class="input-group mt-3">
    <div class="input-group-prepend">
      <span class="input-group-text">金額</span>
    </div>
    <%= form.number_field :yen, class: 'form-control', id: "new-yen", required: true %>
    <div class="ml-2 my-auto">yen</div>
  </div>
  <div class="input-group mt-3">
    <div class="input-group-prepend">
      <span class="input-group-text">予算</span>
    </div>
    <%= form.number_field :remain, class: 'form-control', id: "new-remain", required: true %>
    <div class="ml-2 my-auto">remain</div>
  </div>

  <div class="form-group mt-3">
    <%= form.submit '新規登録', class: 'btn btn-primary btn-block', id: 'new-button' %>
  </div>
<% end %>

app/views/graphs/index.html.erb
<%= Gon::Base.render_data %>
<div class="row">
  <div class="col-6">
    <button type="button" class="btn btn-info btn-block" data-toggle="modal" data-target="#new-modal">
      新規登録
    </button>
  </div>
  <div class="col-6">
    <button type="button" class="btn btn-info btn-block" data-toggle="modal" data-target="#edit-modal">
      記録修正
    </button>
  </div>
</div>
  <div class="row">
  <div class="col-6 col-sm-3">
    <input type="button" value="過去１週間" id="a-week-button" class="btn btn-success btn-block mt-3">
  </div>
  <div class="col-6 col-sm-3">
    <input type="button" value="過去２週間" id="two-weeks-button" class="btn btn-success btn-block mt-3">
  </div>
  <div class="col-6 col-sm-3">
    <input type="button" value="過去１ヶ月" id="a-month-button" class="btn btn-success btn-block mt-3">
  </div>
  <div class="col-6 col-sm-3">
    <input type="button" value="過去３ヶ月" id="three-months-button" class="btn btn-success btn-block mt-3">
  </div>
</div>
<div class="row no-gutters">
  <div class="input-group col-sm-6 pr-sm-3 mt-3">
    <div class="input-group-prepend">
      <span class="input-group-text">開始</span>
    </div>
    <input type="text" id="start-calendar" class="form-control bg-white text-center">
  </div>
  <div class="input-group col-sm-6 pl-sm-3 mt-3">
    <div class="input-group-prepend">
      <span class="input-group-text">終了</span>
    </div>
    <input type="text" id="end-calendar" class="form-control bg-white text-center">
  </div>

<%= render 'modal', action: 'new', title: '新規登録' %>
<%= render 'modal', action: 'edit', title: '修正' %>
<canvas id="chart-yen" class="mt-5"></canvas>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Safekeepingmoney</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'shared/header' %>
   <% if controller_name == 'graphs' %>
    <%= render 'shared/flash_messages' %>
   <% end %>
  <div class="graph-container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-sm navbar-dark bg-primary"> 
    <%= link_to "safekeepingmoney", root_path, class: 'navbar-brand' %>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to 'アカウント編集', edit_user_registration_path, class: 'btn btn-primary' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "アカウント", new_user_registration_path, class: 'btn btn-primary' %>
          </li>
          <li class="nav-item active">
            <%= link_to "ログイン", new_user_session_path, class: 'btn btn-primary' %>
            <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: 'btn btn-primary' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>